apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-prometheus-metrics
  namespace: monitoring
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
#provisioner: ebs.csi.eks.amazonaws.com  # for auto mode clusters
provisioner: ebs.csi.aws.com 
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
  tagSpecification_1: "Name=vol-infra-prod-prometheus-metrics"
reclaimPolicy: Delete   #Deletes the EBS volume when PVC is deleted
allowVolumeExpansion: true   # enables volume resizing