---
replicaCount: 1

connectors:
# in alertmanager, this will be used as http://prometheus-msteams:2000/bar
- bar: <webhook url fo MS Teams channel>
# in alertmanager, this will be used as http://prometheus-msteams:2000/foo
- foo: <webhook url fo MS Teams channel>

image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.5.2
  pullPolicy: Always

imagePullSecrets: []

extraEnvs: {}

container:
  port: 2000
  additionalArgs: 
     - -debug

resources: {}
#  limits:
#    cpu: 10m
#    memory: 32Mi
#  requests:
#    cpu: 1m
#    memory: 8Mi

service:
  type: ClusterIP
  port: 2000

nodeSelector: {}

tolerations: []

affinity: {}

containerSecurityContext: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

priorityClassName: ""

# Custom labels for pod assignment
podLabels: {}

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels: 
      release: prometheus # change this accordingly
    scrapeInterval: 30s

## Specify the custom message card template for MS teams
customCardTemplate: ""
# customCardTemplate: |
#   {{ define "teams.card" }}
#   {...}
#   {{ end }}

templateFile: /etc/template/card.tmpl

extraConfigmapMounts: []
# extraConfigmapMounts:
#   - name: customConfigMap
#     configMap:
#       name: customConfigMapName

## Additional Volume mounts
extraVolumeMounts: []
# extraVolumeMounts:
#   - name: volume-name
#     mountPath: /etc/custom_path

# connectors: []

# ref: https://github.com/prometheus-msteams/prometheus-msteams#customise-messages-per-ms-teams-channel
connectorsWithCustomTemplates: []
# - request_path: /alert2
#   template_file: |
#     {{ define "teams.card" }}
#     {...}
#     {{ end }}
#   webhook_url: <webhook>
#   escape_underscores: true

# Env from existing secrets or configmaps (in same namespace), will passed through to contains 'envFrom'
envFrom: {}
# envFrom:
#   - secretRef:
#       name: my-prometheus-msteams-env-secret
#   - configMapRef:
#       name: my-prometheus-msteams-env-cm

